name: Publish

on:
  push:
    branches:
        - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        python -m pip install -r requirements.txt
        make html
        touch _build/html/.nojekyll
    - name: Push the docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
        publish_branch: latestHTML